In [1]:
# Escenario: Eres analista en un fondo de inversión. Tienes la composición de tu cartera en un DataFrame, pero para evaluar su rendimiento, necesitas cruzar esa información con los precios de mercado actuales. Tu objetivo final es determinar la rentabilidad total por cada sector de tu cartera.

import pandas as pd
import numpy as np

# DataFrame 1: Tu cartera estática (lo que tienes comprado)
cartera_df = pd.DataFrame({
    'ticker': ['AAPL', 'MSFT', 'GOOGL', 'JPM', 'BAC', 'GS'],
    'sector': ['Tech', 'Tech', 'Tech', 'Financials', 'Financials', 'Financials'],
    'cantidad_acciones': [50, 30, 25, 100, 200, 75],
    'precio_compra_unitario': [150.25, 290.80, 135.50, 140.10, 35.20, 350.90]
})

# DataFrame 2: Datos 'frescos' del mercado (los precios de cierre de hoy)
# Nota: Incluimos un ticker ('NVDA') que no está en tu cartera y falta uno ('GS') que sí está.
precios_mercado_df = pd.DataFrame({
    'symbol': ['MSFT', 'AAPL', 'JPM', 'BAC', 'NVDA', 'GOOGL'],
    'precio_cierre_hoy': [310.50, 175.80, 138.50, 38.90, 480.20, 142.30]
})

print("--- Mi Cartera ---")
print(cartera_df)
print("\n--- Precios de Mercado Hoy ---")
print(precios_mercado_df)

--- Mi Cartera ---
  ticker      sector  cantidad_acciones  precio_compra_unitario
0   AAPL        Tech                 50                  150.25
1   MSFT        Tech                 30                  290.80
2  GOOGL        Tech                 25                  135.50
3    JPM  Financials                100                  140.10
4    BAC  Financials                200                   35.20
5     GS  Financials                 75                  350.90

--- Precios de Mercado Hoy ---
  symbol  precio_cierre_hoy
0   MSFT              310.5
1   AAPL              175.8
2    JPM              138.5
3    BAC               38.9
4   NVDA              480.2
5  GOOGL              142.3

In [4]:
# Cambiamos el nombre de la columna symbol a ticker

precios_mercado_df=precios_mercado_df.rename(columns={'symbol':'ticker'})

In [7]:
# Combinamos dataframes

cartera_completa_df=pd.merge(cartera_df, precios_mercado_df, on='ticker', how='left') #Usamos how='left' para que aunque algún activo no tenga toda la información, este se una con Nan
cartera_completa_df

,ticker,sector,cantidad_acciones,precio_compra_unitario,precio_cierre_hoy
0,AAPL,Tech,50,150.25,175.8
1,MSFT,Tech,30,290.80,310.5
2,GOOGL,Tech,25,135.50,142.3
3,JPM,Financials,100,140.10,138.5
4,BAC,Financials,200,35.20,38.9
5,GS,Financials,75,350.90,NaN

In [10]:
# Añadimos columnas que usaremos posteriormente

cartera_completa_df['valor_compra_total']=cartera_completa_df['cantidad_acciones']*cartera_completa_df['precio_compra_unitario']
cartera_completa_df['valor_mercado_actual']=cartera_completa_df['cantidad_acciones']*cartera_completa_df['precio_cierre_hoy']
cartera_completa_df['ganancia_o_pérdida']=cartera_completa_df['valor_mercado_actual']-cartera_completa_df['valor_compra_total']
cartera_completa_df

,ticker,sector,cantidad_acciones,precio_compra_unitario,precio_cierre_hoy,valor_compra_total,valor_mercado_actual,ganancia_o_pérdida
0,AAPL,Tech,50,150.25,175.8,7512.5,8790.0,1277.5
1,MSFT,Tech,30,290.80,310.5,8724.0,9315.0,591.0
2,GOOGL,Tech,25,135.50,142.3,3387.5,3557.5,170.0
3,JPM,Financials,100,140.10,138.5,14010.0,13850.0,-160.0
4,BAC,Financials,200,35.20,38.9,7040.0,7780.0,740.0
5,GS,Financials,75,350.90,NaN,26317.5,NaN,NaN

In [20]:
ganancia_perdida_sector=cartera_completa_df.groupby('sector')['ganancia_o_pérdida'].sum()
activos_total_sector=cartera_completa_df.groupby('sector')['sector'].count()
# activos_total_sector = cartera_completa_df.groupby('sector').size() --> Alternativa/mejora

print(ganancia_perdida_sector)
print("\n")
print(activos_total_sector)

sector
Financials     580.0
Tech          2038.5
Name: ganancia_o_pérdida, dtype: float64


sector
Financials    3
Tech          3
Name: sector, dtype: int64

In [22]:
"""
a) Notamos que en ambos sectores estamos en ganancias, sobre todo en el sector tech.
b) Tenemos 3 activos de cada sector
"""

'\na) Notamos que en ambos sectores estamos en ganancias, sobre todo en el sector tech.\nb) Tenemos 3 activos de cada sector\n'